baseURL = 'https://infosec-academy.github.io/linux-training/'
languageCode = 'en-us'
title = 'Linux Eğitim'
theme = 'hugo-book'
publishDir = "docs"

[[module.mounts]]
  source = 'static'
  target = 'static'